@customer_id = 9e56a0cd-00a6-4386-8412-e8d8ca48da16

### List all records
GET http://localhost:8000/customers

### Create New Record
POST http://localhost:8000/customers
Content-Type: application/json

{
    "firstname": "Jason",
    "lastname" : "Bourne",
    "age" : 40 
}

### Retrieve Single record
GET http://localhost:8000/customers/{{customer_id}}

### Delete Single record
DELETE http://localhost:8000/customers/{{customer_id}}


### Update Single record
PUT http://localhost:8000/customers/{{customer_id}}
Content-Type: application/json

{
    "firstname": "Jason",
    "lastname" : "Bourne",
    "age" : 40 
}

